// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Panca Wanda",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Panca Wanda",
            targets: ["AppModule"],
            bundleIdentifier: "com.dikidwid.Panca-Wanda",
            teamIdentifier: "QJ4D5LRK3T",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad
            ],
            supportedInterfaceOrientations: [
                .portrait
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)